# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 11:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('scale_max', models.IntegerField(blank=True, null=True)),
                ('scale_min', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('sub_type', models.CharField(blank=True, max_length=100, null=True)),
                ('special_category', models.CharField(blank=True, max_length=100, null=True)),
                ('vertical_length', models.IntegerField(blank=True, null=True)),
                ('shape', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Buoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('scale_max', models.IntegerField(blank=True, null=True)),
                ('scale_min', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('sub_type', models.CharField(blank=True, max_length=100, null=True)),
                ('special_category', models.CharField(blank=True, max_length=100, null=True)),
                ('vertical_length', models.IntegerField(blank=True, null=True)),
                ('shape', models.CharField(blank=True, max_length=100, null=True)),
                ('color_patern', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DayMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('scale_max', models.IntegerField(blank=True, null=True)),
                ('scale_min', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('sub_type', models.CharField(blank=True, max_length=100, null=True)),
                ('special_category', models.CharField(blank=True, max_length=100, null=True)),
                ('vertical_length', models.IntegerField(blank=True, null=True)),
                ('top_shape', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('scale_max', models.IntegerField(blank=True, null=True)),
                ('scale_min', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('sub_type', models.CharField(blank=True, max_length=100, null=True)),
                ('special_category', models.CharField(blank=True, max_length=100, null=True)),
                ('vertical_length', models.IntegerField(blank=True, null=True)),
                ('characteristic', models.IntegerField(blank=True, null=True)),
                ('exhibition_condition', models.IntegerField(blank=True, null=True)),
                ('nominal_range', models.IntegerField(blank=True, null=True)),
                ('orientation', models.FloatField(blank=True, null=True)),
                ('signal_group', models.CharField(blank=True, max_length=100, null=True)),
                ('signal_period', models.FloatField(blank=True, null=True)),
                ('signal_sequence', models.CharField(blank=True, max_length=255, null=True)),
                ('visibility', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mooring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('scale_max', models.IntegerField(blank=True, null=True)),
                ('scale_min', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('sub_type', models.CharField(blank=True, max_length=100, null=True)),
                ('special_category', models.CharField(blank=True, max_length=100, null=True)),
                ('vertical_length', models.IntegerField(blank=True, null=True)),
                ('water_level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
